{
 "title": "Confluent Open Source",
 "tags": [ "5.3.0" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(cp_zookeeper_initlimit, release)"
   }
  ]
 },
 "panels": [
  { "title": "Confluent Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_connector_count"
    }
   ]
  },
  {
   "title": "Connector Startup Success Total",
   "type": "singlestat",
   "description": "The total number of connector starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_success_total"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "singlestat",
   "description": "The total number of connector starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_failure_total"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_task_count"
    }
   ]
  },
  {
   "title": "Task Startup Success Total",
   "type": "singlestat",
   "description": "The total number of task starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_success_total"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "singlestat",
   "description": "The total number of task starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_failure_total"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_connect_1_io_ratio"
    }
   ]
  },
  {
   "title": "Connect Metrics: Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_connect_1_incoming_byte_rate",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_connect_1_network_io_rate",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used" }
   ]
  },
  {
   "title": "JVM Threads Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current" }
   ]
  }
 ]
}