global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
# - job_name: 'kafka'
#   static_configs:
#    - targets:
#      - localhost:7071
 - job_name: 'connect'
   static_configs:
    - targets:
      - localhost:7070     
